name: CI

#trigger to run workflow
on: 
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

#define jobs (trong jobs sẽ run nhiều jobs khác nhau)
jobs:
   # job build
  build:
    # run-on (use virtual environment cua github) mac-osx, windows, ubuntu-,...
    runs-on: ubuntu-latest
    # trong job se có nhiều steps:
    steps:
      # name (optional): ten cua step
      - name: Checkout source code
        # actions repo support github to checkout source code
        uses: actions/checkout@v2
      - name: Setup Node version
        # mac dinh se xu dung node version moi nhat action nay de minh define version muon su dung
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Install Dependencies
        run: yarn 
        
      - name: Run test
        run: yarn test --ci
      
      - name: Build Project
        if: github.event_name == 'push'
        run : yarn build
      - name: Upload Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
          
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/head/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Staging
        if : github.event_name == 'push'
        run : npx surge --project ./build --domain abc-apparatus.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

  



      

