name: CI

on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Install Dependencies
        run: yarn 
        env:
          CI: true
      - name: Run test
        run: yarn test
      
      - name: Build Project
        if: github.event_name == 'push'
        run : yarn build
      - name: Deploy Staging
        if : github.event_name == 'push'
        run : npx surge --project ./build --domian silent-apparatus.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

  



      

